### ISSUE TITLE
Crear entorno de la app (app inicial en react native)

### ISSUE THREAD

**Issue by javi11** [javi11/gamer-matcher-app#1]
Inizializar todo lo necesario de react native

- Usa [Eslint airbnbn](https://www.npmjs.com/package/eslint-config-airbnb) para linter del código

**Comment by tOnichoo** [comment]
me lo pido! 
Cuando puedas dame permisos en el proyecto para poder asignarme tickets y poder hacer push.

**Comment by tOnichoo** [comment]
Ojo! para que funcione bien todo lo relacionado con react es recomendable trabajar con una version de npm mas baja de la 5.
Yo he hecho downgrade de la 5 a la 4.6.1 y ha ido de lujo, porque con la 5 me daba problemas al generar la estructura y me decia que react actualmente no esta hecho para aguantar la version 5 de npm.

**Comment by javi11** [comment]
Hola @tOnichoo, bienvenido :P, ahora te doy permisos al repo, por lo de npm no se hasta que punto deberiamos usar mejor aqui yarn que piensas?

Para hacer cambios sigue estos pasos para que podamos tener un buen control.

1. Hazte una rama
2. Haz lo que quieras ahí. Usa si puedes [conventional commit](https://github.com/pvdlg/conventional-commit-types) y en ingles. Referencia la issue cuando la acabes en el commit con Closes #NUMERO DE ISSUE
3. Crea un pull requests a la rama develop una vez acabes.

Creo que eso es todo :), perdon que te lo diga por aquí tengo que escribir la guia de contribución todabía :p 

Mil gracias!!!!
